'use strict';
// Funções utilitárias puras (extraído do index.html)
function clone(obj){return JSON.parse(JSON.stringify(obj));}
function genId(prefix){return prefix+'-'+Date.now().toString(36)+Math.random().toString(36).slice(2,8);}
function capitalizeFirst(value){value=String(value||'');return value?value.charAt(0).toLocaleUpperCase('pt-BR')+value.slice(1):value;}
function formatCpfCnpj(raw){const d=String(raw||'').replace(/\D/g,'').slice(0,14);if(!d)return '';if(d.length<=11){let out=d.slice(0,3);if(d.length>3)out+='.'+d.slice(3,6);if(d.length>6)out+='.'+d.slice(6,9);if(d.length>9)out+='-'+d.slice(9,11);return out;}let out=d.slice(0,2);if(d.length>2)out+='.'+d.slice(2,5);if(d.length>5)out+='.'+d.slice(5,8);if(d.length>8)out+='/'+d.slice(8,12);if(d.length>12)out+='-'+d.slice(12,14);return out;}
function formatPhoneDigits(raw){const d=String(raw||'').replace(/\D/g,'').slice(0,11);if(!d)return '';if(d.length<=2)return '('+d;const ddd=d.slice(0,2);const rest=d.slice(2);if(rest.length<=4)return '('+ddd+') '+rest;if(d.length<=10)return '('+ddd+') '+rest.slice(0,4)+'-'+rest.slice(4);return '('+ddd+') '+rest.slice(0,5)+'-'+rest.slice(5);}
function isValidEmail(value){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(value||'').trim());}
function isValidCPF(digits){if(!/^\d{11}$/.test(digits))return false;if(/^(\d)\1{10}$/.test(digits))return false;let sum=0;for(let i=0;i<9;i++)sum+=parseInt(digits[i],10)*(10-i);let rest=sum%11;const d1=rest<2?0:11-rest;if(d1!==parseInt(digits[9],10))return false;sum=0;for(let i=0;i<10;i++)sum+=parseInt(digits[i],10)*(11-i);rest=sum%11;const d2=rest<2?0:11-rest;return d2===parseInt(digits[10],10);}
function isValidCNPJ(digits){if(!/^\d{14}$/.test(digits))return false;if(/^(\d)\1{13}$/.test(digits))return false;const w1=[5,4,3,2,9,8,7,6,5,4,3,2];let sum=0;for(let i=0;i<12;i++)sum+=parseInt(digits[i],10)*w1[i];let rest=sum%11;const d1=rest<2?0:11-rest;if(d1!==parseInt(digits[12],10))return false;const w2=[6,5,4,3,2,9,8,7,6,5,4,3,2];sum=0;for(let i=0;i<13;i++)sum+=parseInt(digits[i],10)*w2[i];rest=sum%11;const d2=rest<2?0:11-rest;return d2===parseInt(digits[13],10);}
function isValidCpfCnpj(raw){const digits=String(raw||'').replace(/\D/g,'');if(!digits)return true;if(digits.length===11)return isValidCPF(digits);if(digits.length===14)return isValidCNPJ(digits);return false;}
function whatsappUrl(phoneValue){let d=String(phoneValue||'').replace(/\D/g,'');if(!d)return '';if(!d.startsWith('55'))d='55'+d;return 'https://wa.me/'+d;}
function normalizeTextField(name,value){if(name==='email')return String(value||'').trim().toLowerCase();if(name==='cnpj')return formatCpfCnpj(value);if(name==='phone1'||name==='phone2')return formatPhoneDigits(value);if(name==='whatsapp1'||name==='whatsapp2'||name==='buffet'||name==='manipulaCarne'||name==='preparaSushi'||name==='servePratoCru'||name==='fazDelivery')return String(value||'').trim();return capitalizeFirst(String(value||'').trimStart());}
function normalizeDraftFields(){establishmentDraft=establishmentDraft||clone(state.establishment||{});Object.keys(establishmentDraft).forEach(key=>{establishmentDraft[key]=normalizeTextField(key,establishmentDraft[key]);});document.querySelectorAll('[data-establishment-field]').forEach(input=>{input.value=establishmentDraft[input.getAttribute('data-establishment-field')]||'';});updateMapsLink();}
function escapeHtml(value){return String(value==null?'':value).replace(/[&<>"']/g,chr=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[chr]));}
function formatDataBR(iso){if(!iso)return '—';const partes=iso.split('-');if(partes.length!==3)return iso;return partes[2]+'/'+partes[1]+'/'+partes[0];}
function cssSafe(value){return String(value).replace(/[^a-z0-9_-]/gi,'-');}
function scrollToSelector(selector){const target=document.querySelector(selector);if(target){target.scrollIntoView({behavior:'smooth',block:'start'});return true;}return false;}
